# Extend range of prefixed units from engineering (1e+-12) to full (1e+-24)
from .Unit import addprefixed

addprefixed('m',range='full')
addprefixed('g',range='full')
addprefixed('s',range='full')
addprefixed('A',range='full')
addprefixed('K',range='full')
addprefixed('mol',range='full')
addprefixed('cd',range='full')
addprefixed('rad',range='full')
addprefixed('sr',range='full')
addprefixed('Hz',range='full')
addprefixed('N',range='full')
addprefixed('Pa',range='full')
addprefixed('J',range='full')
addprefixed('W',range='full')
addprefixed('C',range='full')
addprefixed('V',range='full')
addprefixed('F',range='full')
addprefixed('Ohm',range='full')
addprefixed('S',range='full')
addprefixed('Wb',range='full')
addprefixed('T',range='full')
addprefixed('H',range='full')
addprefixed('lm',range='full')
addprefixed('lx',range='full')
