# -*- coding: utf-8 -*-
# Extend range of prefixed units from engineering (1e+-12) to full (1e+-24)
from .Unit import *

addPrefixed('m',range='full')
addPrefixed('g',range='full')
addPrefixed('s',range='full')
addPrefixed('A',range='full')
addPrefixed('K',range='full')
addPrefixed('mol',range='full')
addPrefixed('cd',range='full')
addPrefixed('rad',range='full')
addPrefixed('sr',range='full')
addPrefixed('Hz',range='full')
addPrefixed('N',range='full')
addPrefixed('Pa',range='full')
addPrefixed('J',range='full')
addPrefixed('W',range='full')
addPrefixed('C',range='full')
addPrefixed('V',range='full')
addPrefixed('F',range='full')
addPrefixed('Ohm',range='full')
addPrefixed('S',range='full')
addPrefixed('Wb',range='full')
addPrefixed('T',range='full')
addPrefixed('H',range='full')
addPrefixed('lm',range='full')
addPrefixed('lx',range='full')
